// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts.Dtos.Menus;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts.Dtos.Menus;

public class PermissionDto
{
    public MenuModuleDto[] MenuModule { get; set; }

    public string[] CheckedMenu { get; set; }

    public string[] CheckedModule { get; set; }
}
