// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts;
using General.Backend.Application.Contracts.Dtos.Auths;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAuthAppService), typeof(AuthClientProxy))]
public partial class AuthClientProxy : ClientProxyBase<IAuthAppService>, IAuthAppService
{
    public virtual async Task<LoginUserDto> LoginAsync(UserLoginDto input)
    {
        return await RequestAsync<LoginUserDto>(nameof(LoginAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UserLoginDto), input }
        });
    }

    public virtual async Task<UserPermissionDto> GetUserAsync()
    {
        return await RequestAsync<UserPermissionDto>(nameof(GetUserAsync));
    }

    public virtual async Task<CaptchaDto> GetCaptchaAsync()
    {
        return await RequestAsync<CaptchaDto>(nameof(GetCaptchaAsync));
    }

    public virtual async Task<LoginUserDto> RefreshAsync(RefreshTokenCreateDto input)
    {
        return await RequestAsync<LoginUserDto>(nameof(RefreshAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RefreshTokenCreateDto), input }
        });
    }
}
