// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts;
using General.Backend.Application.Contracts.Dtos.Menus;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMenuAppService), typeof(MenuClientProxy))]
public partial class MenuClientProxy : ClientProxyBase<IMenuAppService>, IMenuAppService
{
    public virtual async Task<PermissionDto> GetPermissionAsync(Guid id)
    {
        return await RequestAsync<PermissionDto>(nameof(GetPermissionAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task UpdateAsync(PermissionUpdateDto input)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PermissionUpdateDto), input }
        });
    }
}
