// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts;
using General.Backend.Application.Contracts.Dtos.SystemSettings;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISystemSettingAppService), typeof(SystemSettingClientProxy))]
public partial class SystemSettingClientProxy : ClientProxyBase<ISystemSettingAppService>, ISystemSettingAppService
{
    public virtual async Task<List<SystemSettingDto>> GetListAsync()
    {
        return await RequestAsync<List<SystemSettingDto>>(nameof(GetListAsync));
    }

    public virtual async Task UpdateAsync(SystemSettingsUpdateDto input)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SystemSettingsUpdateDto), input }
        });
    }
}
