// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts;
using General.Backend.Application.Contracts.Dtos.Users;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IUserAppService), typeof(UserClientProxy))]
public partial class UserClientProxy : ClientProxyBase<IUserAppService>, IUserAppService
{
    public virtual async Task<PagedResultDto<UserDto>> GetListAsync(UserQueryDto input)
    {
        return await RequestAsync<PagedResultDto<UserDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UserQueryDto), input }
        });
    }

    public virtual async Task<UserDto> CreateAsync(UserCreateDto input)
    {
        return await RequestAsync<UserDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UserCreateDto), input }
        });
    }

    public virtual async Task<UserDto> UpdateAsync(UserUpdateDto input)
    {
        return await RequestAsync<UserDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UserUpdateDto), input }
        });
    }

    public virtual async Task<UserDto> GetAsync(Guid id)
    {
        return await RequestAsync<UserDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task DeleteAsync(List<Guid> ids)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), ids }
        });
    }

    public virtual async Task<UserDto> UnfreezeAsync(Guid id)
    {
        return await RequestAsync<UserDto>(nameof(UnfreezeAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
