// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.InformationCollection.Application.Contracts.Dtos.Modules;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace General.InformationCollection.Application.Contracts.Dtos.Modules;

public class ModuleDto : EntityDto<Guid>
{
    public string Name { get; set; }

    public string CompiledVersion { get; set; }

    public string CompiledTime { get; set; }

    public string Description { get; set; }

    public DateTime CreationTime { get; set; }
}
