// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts;

public interface IFtpAppService : IApplicationService
{
    Task<List<String>> GetFileNamesAsync(string filePathDirectory);

    Task<bool> ExistAsync(string filePath);
}
