// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts;
using General.Backend.Application.Contracts.Dtos.Menus;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts;

public interface IMenuAppService : IApplicationService
{
    Task<PermissionDto> GetPermissionAsync(Guid id);

    Task UpdateAsync(PermissionUpdateDto input);
}
