// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts;
using General.Backend.Application.Contracts.Dtos.Users;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts;

public interface IUserAppService : IApplicationService
{
    Task<PagedResultDto<UserDto>> GetListAsync(UserQueryDto input);

    Task<UserDto> CreateAsync(UserCreateDto input);

    Task<UserDto> UpdateAsync(UserUpdateDto input);

    Task<UserDto> GetAsync(Guid id);

    Task DeleteAsync(List<Guid> ids);

    Task<UserDto> UnfreezeAsync(Guid id);
}
