// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.InformationCollection.Application.Contracts;
using General.InformationCollection.Application.Contracts.Dtos.Modules;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace General.InformationCollection.Application;

public interface IModuleAppService : IApplicationService
{
    Task<List<ModuleDto>> GetListAsync();

    Task<ModuleDto> GetByNameAsync(string name);
}
