// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.InformationCollection.Application.Contracts;
using General.InformationCollection.Application.Contracts.Dtos.Modules;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace General.InformationCollection.Application;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IModuleAppService), typeof(ModuleClientProxy))]
public partial class ModuleClientProxy : ClientProxyBase<IModuleAppService>, IModuleAppService
{
    public virtual async Task<List<ModuleDto>> GetListAsync()
    {
        return await RequestAsync<List<ModuleDto>>(nameof(GetListAsync));
    }

    public virtual async Task<ModuleDto> GetByNameAsync(string name)
    {
        return await RequestAsync<ModuleDto>(nameof(GetByNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }
}
