// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts.Dtos.Auths;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts.Dtos.Auths;

public class CaptchaDto
{
    public string Key { get; set; }

    public string Text { get; set; }

    public string Img { get; set; }
}
