// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts.Dtos.Auths;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts.Dtos.Auths;

public class UserPermissionDto
{
    public Guid UserId { get; set; }

    public string UserAccount { get; set; }

    public string UserName { get; set; }

    public string Role { get; set; }

    public string RoleName { get; set; }

    public MenuRouterDto[] MenuRouters { get; set; }

    public string[] Modules { get; set; }
}
