// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts.Dtos;
using General.Backend.Application.Contracts.Dtos.Roles;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts.Dtos.Roles;

public class RoleQueryDto : PageAndSortDto
{
    public string Name { get; set; }
}
