// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFtpAppService), typeof(FtpClientProxy))]
public partial class FtpClientProxy : ClientProxyBase<IFtpAppService>, IFtpAppService
{
    public virtual async Task<List<String>> GetFileNamesAsync(string filePathDirectory)
    {
        return await RequestAsync<List<String>>(nameof(GetFileNamesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), filePathDirectory }
        });
    }

    public virtual async Task<bool> ExistAsync(string filePath)
    {
        return await RequestAsync<bool>(nameof(ExistAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), filePath }
        });
    }
}
