// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts;
using General.Backend.Application.Contracts.Dtos.Roles;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application;

public interface IRoleAppService : IApplicationService
{
    Task<PagedResultDto<RoleDto>> GetListAsync(RoleQueryDto input);

    Task<RoleDto> CreateAsync(RoleCreateDto input);

    Task<RoleDto> UpdateAsync(RoleUpdateDto input);

    Task<RoleDto> GetAsync(Guid id);

    Task DeleteAsync(List<Guid> ids);

    Task<List<RoleMapDto>> GetAllRoleAsync();
}
