// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ILocalizationAppService), typeof(LocalizationClientProxy))]
public partial class LocalizationClientProxy : ClientProxyBase<ILocalizationAppService>, ILocalizationAppService
{
    public virtual object GetHelloWorld(string culture)
    {
        //Client Proxy does not support the synchronization method, you should always use asynchronous methods as a best practice
        throw new System.NotImplementedException(); 
    }

    public virtual object GetHelloName(string culture, string name)
    {
        //Client Proxy does not support the synchronization method, you should always use asynchronous methods as a best practice
        throw new System.NotImplementedException(); 
    }
}
