// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts.Dtos.Auths;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts.Dtos.Auths;

public class LoginUserDto
{
    public Guid UserId { get; set; }

    public string UserAccount { get; set; }

    public string UserName { get; set; }

    public string Role { get; set; }

    public string RoleName { get; set; }

    public string AccessToken { get; set; }

    public int ExpiresIn { get; set; }

    public DateTime ExpiresTime { get; set; }

    public string RefreshToken { get; set; }

    public int RefreshExpiresIn { get; set; }

    public DateTime RefreshExpiresTime { get; set; }
}
