// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts.Dtos.Auths;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts.Dtos.Auths;

public class MenuRouterDto
{
    public string Name { get; set; }

    public string Path { get; set; }

    public bool Hidden { get; set; }

    public string Component { get; set; }

    public string Redirect { get; set; }

    public bool AlwaysShow { get; set; }

    public MetaDto Meta { get; set; }

    public MenuRouterDto[] Children { get; set; }
}
