// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts;
using General.Backend.Application.Contracts.Dtos.Roles;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IRoleAppService), typeof(RoleClientProxy))]
public partial class RoleClientProxy : ClientProxyBase<IRoleAppService>, IRoleAppService
{
    public virtual async Task<PagedResultDto<RoleDto>> GetListAsync(RoleQueryDto input)
    {
        return await RequestAsync<PagedResultDto<RoleDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RoleQueryDto), input }
        });
    }

    public virtual async Task<RoleDto> CreateAsync(RoleCreateDto input)
    {
        return await RequestAsync<RoleDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RoleCreateDto), input }
        });
    }

    public virtual async Task<RoleDto> UpdateAsync(RoleUpdateDto input)
    {
        return await RequestAsync<RoleDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RoleUpdateDto), input }
        });
    }

    public virtual async Task<RoleDto> GetAsync(Guid id)
    {
        return await RequestAsync<RoleDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task DeleteAsync(List<Guid> ids)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), ids }
        });
    }

    public virtual async Task<List<RoleMapDto>> GetAllRoleAsync()
    {
        return await RequestAsync<List<RoleMapDto>>(nameof(GetAllRoleAsync));
    }
}
