// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts.Dtos.Roles;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts.Dtos.Roles;

public class RoleDto : AuditedEntityDto<Guid>
{
    public string Code { get; set; }

    public string Name { get; set; }

    public string Remark { get; set; }
}
