// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts.Dtos.SystemSettings;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;
using Volo.Abp.Settings;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts.Dtos.SystemSettings;

public class SystemSettingsUpdateDto
{
    public SettingValue[] Settings { get; set; }
}
