// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts.Dtos.SystemSettings;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts.Dtos.SystemSettings;

public class SystemSettingDto : EntityDto<Guid>
{
    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string Value { get; set; }

    public string ValueType { get; set; }

    public bool Required { get; set; }

    public string Group { get; set; }

    public int Sort { get; set; }

    public bool IsSecret { get; set; }

    public string Regex { get; set; }

    public string Min { get; set; }

    public string Max { get; set; }

    public string Options { get; set; }
}
