// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts.Dtos.Users;
using General.Backend.Domain.Shared.Enums;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts.Dtos.Users;

public class UserDto : AuditedEntityDto<Guid>
{
    public string Account { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public string Contact { get; set; }

    public string Address { get; set; }

    public FrozenStatus IsFrozen { get; set; }

    public Guid[] RoleIds { get; set; }

    public string[] RoleNames { get; set; }
}
