// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using General.Backend.Application.Contracts.Dtos.Auths;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace General.Backend.Application.Contracts.Dtos.Auths;

public class UserLoginDto
{
    public string UserAccount { get; set; }

    public string Password { get; set; }

    public string Captcha { get; set; }

    public string CaptchaTime { get; set; }
}
